#!/bin/bash
set -x

install-packages git wget make gcc python-pip python-iso8601 python-six python-anyjson python-eventlet python-dev python-setuptools

mkdir -p /opt/git
git clone https://github.com/stackforge/murano-agent.git /opt/git/murano-agent
cd /opt/git/murano-agent

if [ "$DISTRO_NAME" = 'debian' ] || [ "$DISTRO_NAME" = 'ubuntu' ]; then
    ./setup.sh install
else
    # rhel7/centos7/fedora
    ./setup-centos.sh install
fi
